### ISSUE TITLE
Unable to run :    TypeError: Cannot read property 'loaders' of undefined

### ISSUE THREAD

**Issue by Akrosid** [OniVe/vue-apollo-typescript-example#2]
Hello I try to run the project.

I run following command:
```sh
# install dependencies
$ npm install # Or yarn install

# serve with hot reload at localhost:3000
$ npm run dev
```

After run dev i got following error:

 ERROR 

  TypeError: Cannot read property 'loaders' of undefined
  
  - index.js:12 Builder.<anonymous>
    /Users/julien/Documents/nuxt/vue-apollo-typescript-example/modules/typescript/index.js:12:20
  
  - utils.js:119 Builder.<anonymous>
    [vue-apollo-typescript-example]/[nuxt]/lib/common/utils.js:119:23
  
  - client.config.js:219 Builder.webpackClientConfig
    [vue-apollo-typescript-example]/[nuxt]/lib/builder/webpack/client.config.js:219:54
  
  - builder.js:487 Builder.webpackBuild
    [vue-apollo-typescript-example]/[nuxt]/lib/builder/builder.js:487:46
  
  - builder.js:168 Builder.build
    [vue-apollo-typescript-example]/[nuxt]/lib/builder/builder.js:168:16

Any idea why ?

**Comment by OniVe** [comment]
@Akrosid, Try using this solution: [nuxt-community/typescript-template](https://github.com/nuxt-community/typescript-template/issues/11#issuecomment-327693159)
